### ISSUE TITLE
py3 branch, map object is not subscriptable

### ISSUE THREAD

**Issue by dan9thsense** [pvrancx/gym-pinball#1]
I am new to gym and tried to use gym-pinball, branch py3, but got this error:

python3 gym_pinball_mine.py 
[2018-05-08 16:40:55,953] Making new env: PinBall-v0
Traceback (most recent call last):
  File "gym_pinball_mine.py", line 6, in <module>
    env.render()
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 174, in render
    return self._render(mode=mode, close=close)
  File ".../third_party_software/gym-pinball/gym_pinball/envs/pinball_env.py", line 189, in _render
    obj = rendering.make_polyline(points+[points[0]])
TypeError: 'map' object is not subscriptable

Here is the script I used:
```
import gym
import gym_pinball
env = gym.make('PinBall-v0')
env.reset()
t = 0
while True:
    env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    #print("observation:")
    #print(" ".join("{0:.2f}".format(f) for f in observation))
    #print("action = {0:.2f}, reward = {0:.2f}".format(action, reward))
    t += 1
    if done:
       print("Done after {} steps".format(t+1))
       break
```

**Comment by dan9thsense** [comment]
I changed line 188 from:
points = map(lambda p: (p[0]*screen_width,p[1]*screen_height),
                             obs.points)
to:
points = list(map(lambda p: (p[0]*screen_width,p[1]*screen_height),
                             obs.points))

and now it runs without an error (also had to fix the line for import util), but there is no output.
